name: Build sbe binaries

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm install
    - name: Package
      run: npm run dist
    - name: Cleanup artifacts
    - run: npx rimraf "dist/!(*.exe|*.deb|*.AppImage|*.dmg)"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "dist/**"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
