name: Build sbe binaries

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: npm install
    - name: package
      run: npm run dist
    - name: release for macOS
      uses: softprops/action-gh-release@v1
      with:
        files: |
          "dist/*.dmg"
          "dist/*.exe"
      env:
        GITHUB_TOKEN: ${{ secrets.RL_TOKEN }}
