name: Build binaries

on:
  workflow_dispatch:
    inputs:
      beta:
        description: 'Build with Electron beta'
        required: true
        type: boolean
        default: false

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Install Electron beta
      if: ${{ inputs.beta }}
      run: npm install electron@beta
    - name: Package
      run: npm run pack
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: package-${{ matrix.os }}
        path: dist/**
