name: Build sbe binaries

on: [push]
  branches:
    - refs/tags/*

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: build app
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: npm install

    - name: package for macOS
      if: matrix.os == 'macos-latest'
      run: |
        npm run package-macos
        zip -ry sbe-darwin-x64/sbe-macos.zip sbe-darwin-x64/sbe.app
    - name: archive package for macOS
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@master
      with:
        name: sbe-master-macos
        path: ./sbe-darwin-x64/sbe-macos.zip

    - name: package for Windows
      if: matrix.os == 'windows-latest'
      run: npm run package-win32
    - name: zip package for Windows
      if: matrix.os == 'windows-latest'
      run: powershell Compress-Archive -Path sbe-win32-x64 -DestinationPath sbe-windows.zip
    - name: archive package for Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@master
      with:
        name: sbe-master-windows
        path: sbe-windows.zip
