name: Build Electron app

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: build app
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install, package for macOS
      if: matrix.os == 'macos-latest'
      run: |
        ls -l
        node -v
        npm -v
        npm install
        ls -l node_modules
        npm run package-macos
        ls -l sbe-darwin-x64/sbe.app
        zip -r sbe-darwin-x64/sbe-master-macos.zip sbe-darwin-x64/sbe.app
        ls -l sbe-darwin-x64
      env:
        CI: true
    - name: npm install, package for Windows
      if: matrix.os == 'windows-latest'
      run: |
        cd
        node -v
        dir
        npm install
        dir node_modules
        npm run package-win32
#        powershell Compress-Archive -Path sbe-win32-x64 -DestinationPath sbe-master-win32.zip
      env:
        CI: true
#    - name: archive package for macOS
#      if: matrix.os == 'macos-latest'
#      uses: actions/upload-artifact@master
#      with:
#        name: sbe-master-macos
#        path: ./sbe-darwin-x64/sbe-master-macos.zip
#    - name: archive package for Windows
#      if: matrix.os == 'windows-latest'
#      uses: actions/upload-artifact@master
#      with:
#        name: sbe-master-windows
#        path: sbe-master-win32.zip
