name: Electron pre-release

on:
  workflow_dispatch:
    inputs:
      electronVersion:
        description: "Version of Electron"
        required: true
        default: "13.0.0-beta.3"

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    env:
      ELECTRON_VERSION: ${{ github.event.inputs.electronVersion }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Install Electron pre-release
      if: matrix.os != 'windows-latest'
      run: npm install electron@$ELECTRON_VERSION
    - name: Install Electron pre-release (Windows)
      if: matrix.os == 'windows-latest'
      run: npm install electron@%ELECTRON_VERSION%
    - name: Run Test
      run: npm test
    - name: Upload screenshots
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: screenshots_${{ matrix.os }}
        path: src/__test__/screenshot
