name: Electron pre-release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Install Electron beta
      run: npm install electron@beta
    - name: Package
      run: npm run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Cleanup artifacts (Windows)
      if: matrix.os == 'windows-latest'
      run: npx rimraf "dist/!(*.exe)"
    - name: Cleanup artifacts (except Windows)
      if: matrix.os != 'windows-latest'
      run: npx rimraf "dist/!(*.deb|*.AppImage|*.dmg)"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package-${{ matrix.os }}
        path: dist/**
