name: OS Matrix

on: [push, workflow_dispatch]


jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    env:
      ELECTRON_VERSION: 11.0.0-beta.20

    steps:
    - uses: actions/checkout@v2
    - name: Setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Replace electron version
      if: matrix.os != 'macos-latest'
      run: sed -i 's|\^10.1.4|$ELECTRON_VERSION|' package.json
    - name: Replace electron version(macOS)
      if: matrix.os == 'macos-latest'
      run: sed -i '' 's|\^10.1.4|$ELECTRON_VERSION|' package.json
    - name: Install dependencies
      run: npm install
    - name: Run Test
      run: npm test
    - name: Upload screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots_${{ matrix.os }}
        path: src/__test__/screenshot
