name: Electron pre-release

on:
  workflow_dispatch:
    inputs:
      electronVersion:
        description: "Version of Electron"
        required: true
        default: "11.0.0-beta.20"

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm install
    - name: Install Electron pre-release
      run: npm install electron@{{ github.event.inputs.electronVersion }}
    - name: Run Test
      run: npm test
    - name: Upload screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots_${{ matrix.os }}
        path: src/__test__/screenshot
