name: Release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Package (Windows / Linux)
      if: matrix.os != 'macos-latest'
      run: npm run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Package (macOS)
      if: matrix.os == 'macos-latest'
      run: npx electron-builder --mac --universal
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Cleanup artifacts (Windows)
      if: matrix.os == 'windows-latest'
      run: npx rimraf "dist/!(*.exe)"
    - name: Cleanup artifacts (except Windows)
      if: matrix.os != 'windows-latest'
      run: npx rimraf "dist/!(*.deb|*.AppImage|*.dmg)"
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "dist/**"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
